# ~/.config/tmux/tmux.conf

set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

set-option -g default-shell /opt/homebrew/bin/bash
set-option -g default-command /opt/homebrew/bin/bash


set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

setw -g mode-keys vi
set -g history-limit 50000

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux reloaded"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind z resize-pane -Z

set -g status-position bottom
set -g status-left "#[bold] #S "
set -g status-right "%Y-%m-%d %H:%M "
bind w display-popup -E -w 80% -h 70% "tmux-fzf"
bind t display-popup -E -w 60% -h 40% "ti"

# copy paste
setw -g mode-keys vi
set -g set-clipboard on
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
