return {
    "nvim-treesitter/nvim-treesitter",
    lazy = false,
    build = ":TSUpdate",
    opts = {
        ensure_installed = {
            "bash",
            "comment",
            "go",
            "gomod",
            "gosum",
            "gotmpl",
            "gowork",
            "html",
            "javascript",
            "json",
            "lua",
            "markdown",
            "markdown_inline",
            "python",
            "query",
            "regex",
            "sql",
            "tsx",
            "typescript",
            "vim",
            "yaml",
        },
    },
}
